inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: not_to

Rails/DynamicFindBy:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/AndOr:
  EnforcedStyle: conditionals